"""Create players tables

Revision ID: 3151284e5967
Revises: 
Create Date: 2026-01-30 09:30:08.810515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3151284e5967'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('tag_line', sa.String(), nullable=False),
    sa.Column('summoner_level', sa.Integer(), nullable=True),
    sa.Column('profile_icon_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_puuid'), 'players', ['puuid'], unique=True)
    op.create_table('match_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('game_mode', sa.String(), nullable=True),
    sa.Column('game_duration', sa.Integer(), nullable=True),
    sa.Column('game_creation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('champion_name', sa.String(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('total_damage', sa.Integer(), nullable=True),
    sa.Column('gold_earned', sa.Integer(), nullable=True),
    sa.Column('cs', sa.Integer(), nullable=True),
    sa.Column('vision_score', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_history_id'), 'match_history', ['id'], unique=False)
    op.create_index(op.f('ix_match_history_match_id'), 'match_history', ['match_id'], unique=True)
    op.create_table('ranked_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('queue_type', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('lp', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('winrate', sa.Float(), nullable=True),
    sa.Column('veteran', sa.Boolean(), nullable=True),
    sa.Column('hot_streak', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranked_stats_id'), 'ranked_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranked_stats_id'), table_name='ranked_stats')
    op.drop_table('ranked_stats')
    op.drop_index(op.f('ix_match_history_match_id'), table_name='match_history')
    op.drop_index(op.f('ix_match_history_id'), table_name='match_history')
    op.drop_table('match_history')
    op.drop_index(op.f('ix_players_puuid'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
